AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/migrate/*'
  TargetRubyVersion: 2.5

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 400  # Maximum line length from `rails new`

Metrics/ClassLength:
  Max: 1000

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
